name: Electron Build

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4  # Checkout the code

      # Step 2: Set up Node.js with caching
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Step 3: Install dependencies
      - run: npm ci  # Install dependencies

      # Step 4: Install Wine (for Windows builds)
      - name: Install Wine for Windows builds
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32
          npm uninstall dmg-builder
          rm -rf node_modules
          npm install

      # Step 5: Build the app for Linux and Windows
      - run: npm run build --linux --win

      # Step 6: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-build-artifacts  # Name for the artifact
          path: dist/  # Path to the folder where build artifacts are stored (e.g., .AppImage, .exe)
