name: Electron Build

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment

    steps:
      - uses: actions/checkout@v4  # Checkout the code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm ci  # Install dependencies

      - name: Install Wine for Windows builds (if necessary)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32

      - run: npm run build --win --linux  # Ensure macOS is not part of the build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-build-artifacts  # Name for the artifact
          path: dist/  # Path to the folder where build artifacts are stored
